[package]
name = "lumia-app"
version = "0.1.1"
authors = ["iFence"]
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
async-channel.workspace = true
chrono.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
image.workspace = true
lumia-core.workspace = true
lumia-plugin-api.workspace = true
lumia-plugin-host.workspace = true
rfd.workspace = true
serde.workspace = true
serde_json.workspace = true

[package.metadata.wix]
upgrade-guid = "07618386-59ac-4b5c-b4e1-ebe4f8aa182e"
icon = "resources/icon.ico"
language = 1033
platform = "x64"

[package.metadata.wix.start-menu]
name = "Lumia"
working-directory = "INSTALLDIR"

[[package.metadata.wix.shortcut]]
location = "Desktop"
name = "Lumia"

[target.'cfg(windows)'.dependencies]
winreg = "0.54"
windows-sys.workspace = true

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
