[workspace]
members = [
    "crates/lumia-app",
    "crates/lumia-core",
    "crates/lumia-plugin-api",
    "crates/lumia-plugin-host",
    "plugins/lumia-plugin-sample",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
repository = "https://github.com/iFence/lumia"
rust-version = "1.82"

[workspace.dependencies]
anyhow = "1.0.95"
gpui = "=0.2.2"
lumia-core = { path = "crates/lumia-core" }
lumia-plugin-api = { path = "crates/lumia-plugin-api" }
lumia-plugin-host = { path = "crates/lumia-plugin-host" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
thiserror = "2.0.11"
uuid = { version = "1.11.0", features = ["serde", "v7"] }
